export const allBanks = [
  { label: "Allahabad Bank", sector: "Public" },
  { label: "Andhra Bank", sector: "Public" },
  { label: "Bank of Baroda", sector: "Public" },
  { label: "Bank of India", sector: "Public" },
  { label: "Bank of Maharashtra", sector: "Public" },
  { label: "Canara Bank", sector: "Public" },
  { label: "Central Bank of India", sector: "Public" },
  { label: "Corporation Bank", sector: "Public" },
  { label: "Dena Bank", sector: "Public" },
  { label: "Indian Bank", sector: "Public" },
  { label: "Indian Overseas Bank", sector: "Public" },
  { label: "Oriental Bank of Commerce", sector: "Public" },
  { label: "Punjab & Sind Bank", sector: "Public" },
  { label: "Punjab National Bank", sector: "Public" },
  { label: "Syndicate Bank", sector: "Public" },
  { label: "UCO Bank", sector: "Public" },
  { label: "Union Bank of India", sector: "Public" },
  { label: "United Bank Of India (UBI)", sector: "Public" },
  { label: "Vijaya Bank", sector: "Public" },
  { label: "IDBI Bank Limited", sector: "Public" },
];
